version: '3.7'

services:
    flask-app:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - opentelemetry-collector
        networks:
            - monitering
        environment:
            OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector:4317"
            OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
            OTEL_EXPORTER_OTLP_INSECURE: "true"

    opentelemetry-collector:
        image: otel/opentelemetry-collector-contrib:latest
        container_name: opentelemetry-collector
        volumes:
            - ./config/collector/config.yml/:/etc/opentelemetry-collector.yml
        command:
            - "--config=/etc/opentelemetry-collector.yml"
        networks:
            - monitering
        ports:
            - 4317:4317
networks:
    monitering:
